### ISSUE TITLE
crash in sdk when dev machine returning from sleep mode

### ISSUE THREAD

**Issue by erlend-sh** [jMonkeyEngine/sdk#11] opened 2016-03-05 20:20 UTC
_From @ghost on March 24, 2014 19:35_

Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=582

> I have noticed the SDK crashes when returning from sleep mode. I believe this to be related to the openGL preview window that is available in the SDK.
> 
> Crash 1: returning from sleep mode, openGL preview is up already displaying a model. crash throws many blank error boxes, must force quit application.
> 
> Crash 2: returning from sleep mode, openGL preview is not up. I added a model via import, when I went to go preview it in the SDK then crashed the same as before. Major note: SDK then went on to delete the original model file from my disk; luckily the model was still open in Blender, so I simply resaved the file and re-wrote it to disk.
> 
> Windows 8, 64bit

_Copied from original issue: jMonkeyEngine/jmonkeyengine#93_

**Comment by MeFisto94** [comment] 2016-03-17 07:49
I tried this on Mac OS X 10.9.5 and can't reproduce it (even the Controls continue working), so it's a corner case with W8 64bit it seems.

Feel free to test it but keep TaskManager and copies of your models open ;)

**Comment by grizeldi** [comment] 2016-03-17 08:40
I'll try it on my Win7 tonight if it helps.

**Comment by EpicestGamer** [comment] 2017-01-17 23:14
Didn't happen on my window 10 computer

**Comment by MeFisto94** [comment] 2018-01-31 12:10
No one had that problem for almost 4 years now, so I'll close this. In case someone experiences this, feel free to comment here (most people are going to create a new issue anyway)

**Closed by MeFisto94** 2018-01-31 12:10 UTC
Labels: bug, needs testing
