### ISSUE TITLE
.j3md braces issue

### ISSUE THREAD

**Issue by erlend-sh** [jMonkeyEngine/sdk#5] opened 2016-03-05 20:19 UTC
_From @FrozenShade666 on November 23, 2015 7:29_

Having braces in next line in j3md file results in empty parameters list while creating/editing j3m file in SDK 3.0. I don't know if the problem exists in 3.1.
The engine itself can handle such syntax and all materials are processed correctly.

_Copied from original issue: jMonkeyEngine/jmonkeyengine#386_

**Comment by MeFisto94** [comment] 2016-03-16 22:42
I actually talked to FrozenShade and he doesn't have the exact file for testing anymore.
Also we don't know if this is present in 3.1 anymore.
I wasn't able to reproduce it, but I have only tried it a bit so there might still be corner cases.

I'll close this issue once someone has confirmed that he cannot reproduce this issue.

**Comment by MeFisto94** [comment] 2018-01-31 12:12
I'm closing this now, if someone can come up with the problem, feel free to comment/reopen.
Chances are that this used to be an odd corner case / bug in the engine though, since I guess the SDK won't have it's own j3md parser.

**Closed by MeFisto94** 2018-01-31 12:12 UTC
Labels: needs testing
