### ISSUE TITLE
splash screen needs updating for v3.2

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/sdk#146] opened 2018-01-07 00:23 UTC
/master/branding/core/core.jar/org/netbeans/core/startup/splash.gif still indicates "SDK 3.1"

**Comment by grizeldi** [comment] 2018-01-07 10:11
Duplicate of #124

**Comment by MeFisto94** [comment] 2018-01-07 15:14
I've got a hold of the source files, I'll update them asap. I'm unsure whether to upload those files or not, since we don't want derivative work of that. On the other hand, that's covered by the BSD License...

**Comment by MeFisto94** [comment] 2018-01-07 15:37
I've now taken the creative freedom to color-code the versions. 3.2 is red, 3.3 will be green, 3.4 will be blue (just like RGB). After that 3.5 will be the monkey-yellow and 3.6 we'll have to decide.

Note: If people dislike those colors, I might change this again starting 3.3

**Closed by MeFisto94** 2018-01-07 15:37 UTC

**Comment by grizeldi** [comment] 2018-01-08 06:14
Although the idea of color coding is good, that color feels out of place. Either repaint all yellow or nothing.
