### ISSUE TITLE
An Exception has occured in the SDK (JMonkey v3.2.4-Stable-SDK1).

### ISSUE THREAD

**Issue by zethan191** [jMonkeyEngine/sdk#195] opened 2019-07-30 17:38 UTC
Hi there,

This problem occurred when I was trying to open "UnshadedArray.j3d" from "jme3test.texture".

Thank you.

"Error Details" tab:
------------------------------------------------------------------------------
jMonkeyEngine SDK Exception Report
Please submit me to the Issue Tracker
Comment: This means that there was an unexpected exception when parsing the j3md. If this was due to you opening a j3md from a jar (org.openide.filesystems.FSException) then don't report it to us, if it differs, do so!
com.jme3.asset.AssetNotFoundException: /home/erick/JmeTests/src/jme3test/texture/UnshadedArray.j3md
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:370)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:386)
	at com.jme3.gde.materialdefinition.EditableMatDefFile.load(EditableMatDefFile.java:138)
	at com.jme3.gde.materialdefinition.EditableMatDefFile.<init>(EditableMatDefFile.java:102)
	at com.jme3.gde.materialdefinition.MatDefDataObject.getEditableFile(MatDefDataObject.java:288)
	at com.jme3.gde.materialdefinition.navigator.MatDefNavigatorPanel.updateData(MatDefNavigatorPanel.java:127)
	at com.jme3.gde.materialdefinition.MatDefDataObject.createEditor(MatDefDataObject.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.netbeans.core.spi.multiview.MultiViewFactory$MapMVD.createElement(MultiViewFactory.java:456)
	at org.netbeans.core.multiview.MultiViewModel.getElementForDescription(MultiViewModel.java:222)
	at org.netbeans.core.multiview.MultiViewModel.getActiveElement(MultiViewModel.java:132)
	at org.netbeans.core.multiview.MultiViewModel.getActiveElement(MultiViewModel.java:128)
	at org.netbeans.core.multiview.MultiViewPeer.peerComponentShowing(MultiViewPeer.java:335)
	at org.netbeans.core.multiview.MultiViewCloneableTopComponent.componentShowing(MultiViewCloneableTopComponent.java:134)
	at org.openide.windows.WindowManager.componentShowing(WindowManager.java:339)
	at org.netbeans.core.windows.WindowManagerImpl.componentShowing(WindowManagerImpl.java:1200)
	at org.netbeans.core.windows.view.DefaultView.changeGUI(DefaultView.java:168)
	at org.netbeans.core.windows.ViewRequestor.dispatchRequest(ViewRequestor.java:275)
	at org.netbeans.core.windows.ViewRequestor.processRequest(ViewRequestor.java:251)
	at org.netbeans.core.windows.ViewRequestor.postRequest(ViewRequestor.java:189)
	at org.netbeans.core.windows.ViewRequestor.scheduleRequest(ViewRequestor.java:127)
	at org.netbeans.core.windows.Central.addModeOpenedTopComponent(Central.java:791)
	at org.netbeans.core.windows.ModeImpl.addOpenedTopComponent(ModeImpl.java:354)
	at org.netbeans.core.windows.WindowManagerImpl.topComponentOpenAtTabPosition(WindowManagerImpl.java:1261)
	at org.netbeans.core.windows.WindowManagerImpl.topComponentOpen(WindowManagerImpl.java:1226)
	at org.openide.windows.TopComponent.open(TopComponent.java:497)
	at org.openide.windows.TopComponent.open(TopComponent.java:477)
	at org.openide.windows.CloneableOpenSupport.openCloneableTopComponent(CloneableOpenSupport.java:208)
	at org.openide.windows.CloneableOpenSupport$1.run(CloneableOpenSupport.java:107)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEvent(NbMutexEventProvider.java:118)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.writeAccess(NbMutexEventProvider.java:83)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.writeAccess(LazyMutexImplementation.java:79)
	at org.openide.util.Mutex.writeAccess(Mutex.java:310)
	at org.openide.windows.CloneableOpenSupport.open(CloneableOpenSupport.java:104)
	at org.openide.text.CloneableEditorSupport.open(CloneableEditorSupport.java:436)
	at org.openide.awt.ActionDefaultPerfomer.actionPerformed(ActionDefaultPerfomer.java:70)
	at org.openide.awt.ContextAction$Performer.actionPerformed(ContextAction.java:226)
	at org.openide.awt.ContextManager.actionPerformed(ContextManager.java:260)
	at org.openide.awt.ContextAction.actionPerformed(ContextAction.java:109)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:93)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
	at org.openide.awt.GeneralAction$BaseDelAction.actionPerformed(GeneralAction.java:234)
	at org.openide.explorer.view.TreeView$PopupSupport.mouseClicked(TreeView.java:1609)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Operating System: Linux
Engine Version as used by the SDK: 3.2-stable

Graphics Capabilities
---------------------
FrameBuffer
FrameBufferMRT
FrameBufferMultisample
TextureMultisample
OpenGL20
OpenGL21
OpenGL30
OpenGL31
OpenGL32
OpenGL33
OpenGL40
OpenGL41
OpenGL42
OpenGL43
OpenGL44
OpenGL45
GLSL100
GLSL110
GLSL120
GLSL130
GLSL140
GLSL150
GLSL330
GLSL400
GLSL410
GLSL420
GLSL430
GLSL440
GLSL450
VertexTextureFetch
GeometryShader
TesselationShader
TextureArray
TextureBuffer
FloatTexture
IntegerTexture
FloatColorBuffer
FloatDepthBuffer
PackedFloatTexture
SharedExponentTexture
PackedFloatColorBuffer
NonPowerOfTwoTextures
MeshInstancing
VertexBufferArray
Multisample
PackedDepthStencilBuffer
Srgb
FrameBufferBlit
TextureCompressionS3TC
TextureFilterAnisotropic
TextureCompressionETC1
TextureCompressionETC2
DepthTexture
IntegerIndexBuffer
SeamlessCubemap
BinaryShader

**Comment by zethan191** [comment] 2019-07-30 17:42
Here is the second one, which happened, when I was trying to open "text3D.j3md" from "jme3test.texture" project.

Thank you.

"Error Details" tab:
---------------------------------------------------------------
jMonkeyEngine SDK Exception Report
Please submit me to the Issue Tracker
Comment: This means that there was an unexpected exception when parsing the j3md. If this was due to you opening a j3md from a jar (org.openide.filesystems.FSException) then don't report it to us, if it differs, do so!
com.jme3.asset.AssetNotFoundException: /home/erick/JmeTests/src/jme3test/texture/tex3D.j3md
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:370)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:386)
	at com.jme3.gde.materialdefinition.EditableMatDefFile.load(EditableMatDefFile.java:138)
	at com.jme3.gde.materialdefinition.EditableMatDefFile.<init>(EditableMatDefFile.java:102)
	at com.jme3.gde.materialdefinition.MatDefDataObject.getEditableFile(MatDefDataObject.java:288)
	at com.jme3.gde.materialdefinition.navigator.MatDefNavigatorPanel.updateData(MatDefNavigatorPanel.java:127)
	at com.jme3.gde.materialdefinition.MatDefDataObject.createEditor(MatDefDataObject.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.netbeans.core.spi.multiview.MultiViewFactory$MapMVD.createElement(MultiViewFactory.java:456)
	at org.netbeans.core.multiview.MultiViewModel.getElementForDescription(MultiViewModel.java:222)
	at org.netbeans.core.multiview.MultiViewModel.getActiveElement(MultiViewModel.java:132)
	at org.netbeans.core.multiview.MultiViewModel.getActiveElement(MultiViewModel.java:128)
	at org.netbeans.core.multiview.MultiViewPeer.peerComponentShowing(MultiViewPeer.java:335)
	at org.netbeans.core.multiview.MultiViewCloneableTopComponent.componentShowing(MultiViewCloneableTopComponent.java:134)
	at org.openide.windows.WindowManager.componentShowing(WindowManager.java:339)
	at org.netbeans.core.windows.WindowManagerImpl.componentShowing(WindowManagerImpl.java:1200)
	at org.netbeans.core.windows.view.DefaultView.changeGUI(DefaultView.java:168)
	at org.netbeans.core.windows.ViewRequestor.dispatchRequest(ViewRequestor.java:275)
	at org.netbeans.core.windows.ViewRequestor.processRequest(ViewRequestor.java:251)
	at org.netbeans.core.windows.ViewRequestor.postRequest(ViewRequestor.java:189)
	at org.netbeans.core.windows.ViewRequestor.scheduleRequest(ViewRequestor.java:127)
	at org.netbeans.core.windows.Central.addModeOpenedTopComponent(Central.java:791)
	at org.netbeans.core.windows.ModeImpl.addOpenedTopComponent(ModeImpl.java:354)
	at org.netbeans.core.windows.WindowManagerImpl.topComponentOpenAtTabPosition(WindowManagerImpl.java:1261)
	at org.netbeans.core.windows.WindowManagerImpl.topComponentOpen(WindowManagerImpl.java:1226)
	at org.openide.windows.TopComponent.open(TopComponent.java:497)
	at org.openide.windows.TopComponent.open(TopComponent.java:477)
	at org.openide.windows.CloneableOpenSupport.openCloneableTopComponent(CloneableOpenSupport.java:208)
	at org.openide.windows.CloneableOpenSupport$1.run(CloneableOpenSupport.java:107)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEvent(NbMutexEventProvider.java:118)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.writeAccess(NbMutexEventProvider.java:83)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.writeAccess(LazyMutexImplementation.java:79)
	at org.openide.util.Mutex.writeAccess(Mutex.java:310)
	at org.openide.windows.CloneableOpenSupport.open(CloneableOpenSupport.java:104)
	at org.openide.text.CloneableEditorSupport.open(CloneableEditorSupport.java:436)
	at org.openide.awt.ActionDefaultPerfomer.actionPerformed(ActionDefaultPerfomer.java:70)
	at org.openide.awt.ContextAction$Performer.actionPerformed(ContextAction.java:226)
	at org.openide.awt.ContextManager.actionPerformed(ContextManager.java:260)
	at org.openide.awt.ContextAction.actionPerformed(ContextAction.java:109)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:93)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
	at org.openide.awt.GeneralAction$BaseDelAction.actionPerformed(GeneralAction.java:234)
	at org.openide.explorer.view.TreeView$PopupSupport.mouseClicked(TreeView.java:1609)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Operating System: Linux
Engine Version as used by the SDK: 3.2-stable

Graphics Capabilities
---------------------
FrameBuffer
FrameBufferMRT
FrameBufferMultisample
TextureMultisample
OpenGL20
OpenGL21
OpenGL30
OpenGL31
OpenGL32
OpenGL33
OpenGL40
OpenGL41
OpenGL42
OpenGL43
OpenGL44
OpenGL45
GLSL100
GLSL110
GLSL120
GLSL130
GLSL140
GLSL150
GLSL330
GLSL400
GLSL410
GLSL420
GLSL430
GLSL440
GLSL450
VertexTextureFetch
GeometryShader
TesselationShader
TextureArray
TextureBuffer
FloatTexture
IntegerTexture
FloatColorBuffer
FloatDepthBuffer
PackedFloatTexture
SharedExponentTexture
PackedFloatColorBuffer
NonPowerOfTwoTextures
MeshInstancing
VertexBufferArray
Multisample
PackedDepthStencilBuffer
Srgb
FrameBufferBlit
TextureCompressionS3TC
TextureFilterAnisotropic
TextureCompressionETC1
TextureCompressionETC2
DepthTexture
IntegerIndexBuffer
SeamlessCubemap
BinaryShader

**Comment by zethan191** [comment] 2019-07-30 22:14
Here is the similar issue, but on different computer. Opened "tex3DThumb.j3md" in "jme3test.texture" project.

"Error Details" tab:
-------------------------------------------------------------
jMonkeyEngine SDK Exception Report
Please submit me to the Issue Tracker
Comment: This means that there was an unexpected exception when parsing the j3md. If this was due to you opening a j3md from a jar (org.openide.filesystems.FSException) then don't report it to us, if it differs, do so!
com.jme3.asset.AssetNotFoundException: /home/erick/JmeTests/src/jme3test/texture/tex3DThumb.j3md
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:370)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:386)
	at com.jme3.gde.materialdefinition.EditableMatDefFile.load(EditableMatDefFile.java:138)
	at com.jme3.gde.materialdefinition.EditableMatDefFile.<init>(EditableMatDefFile.java:102)
	at com.jme3.gde.materialdefinition.MatDefDataObject.getEditableFile(MatDefDataObject.java:288)
	at com.jme3.gde.materialdefinition.navigator.MatDefNavigatorPanel.updateData(MatDefNavigatorPanel.java:127)
	at com.jme3.gde.materialdefinition.MatDefDataObject.createEditor(MatDefDataObject.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.netbeans.core.spi.multiview.MultiViewFactory$MapMVD.createElement(MultiViewFactory.java:456)
	at org.netbeans.core.multiview.MultiViewModel.getElementForDescription(MultiViewModel.java:222)
	at org.netbeans.core.multiview.MultiViewModel.getActiveElement(MultiViewModel.java:132)
	at org.netbeans.core.multiview.MultiViewModel.getActiveElement(MultiViewModel.java:128)
	at org.netbeans.core.multiview.MultiViewPeer.peerComponentShowing(MultiViewPeer.java:335)
	at org.netbeans.core.multiview.MultiViewCloneableTopComponent.componentShowing(MultiViewCloneableTopComponent.java:134)
	at org.openide.windows.WindowManager.componentShowing(WindowManager.java:339)
	at org.netbeans.core.windows.WindowManagerImpl.componentShowing(WindowManagerImpl.java:1200)
	at org.netbeans.core.windows.view.DefaultView.changeGUI(DefaultView.java:168)
	at org.netbeans.core.windows.ViewRequestor.dispatchRequest(ViewRequestor.java:275)
	at org.netbeans.core.windows.ViewRequestor.processRequest(ViewRequestor.java:251)
	at org.netbeans.core.windows.ViewRequestor.postRequest(ViewRequestor.java:189)
	at org.netbeans.core.windows.ViewRequestor.scheduleRequest(ViewRequestor.java:127)
	at org.netbeans.core.windows.Central.addModeOpenedTopComponent(Central.java:791)
	at org.netbeans.core.windows.ModeImpl.addOpenedTopComponent(ModeImpl.java:354)
	at org.netbeans.core.windows.WindowManagerImpl.topComponentOpenAtTabPosition(WindowManagerImpl.java:1261)
	at org.netbeans.core.windows.WindowManagerImpl.topComponentOpen(WindowManagerImpl.java:1226)
	at org.openide.windows.TopComponent.open(TopComponent.java:497)
	at org.openide.windows.TopComponent.open(TopComponent.java:477)
	at org.openide.windows.CloneableOpenSupport.openCloneableTopComponent(CloneableOpenSupport.java:208)
	at org.openide.windows.CloneableOpenSupport$1.run(CloneableOpenSupport.java:107)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEvent(NbMutexEventProvider.java:118)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.writeAccess(NbMutexEventProvider.java:83)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.writeAccess(LazyMutexImplementation.java:79)
	at org.openide.util.Mutex.writeAccess(Mutex.java:310)
	at org.openide.windows.CloneableOpenSupport.open(CloneableOpenSupport.java:104)
	at org.openide.text.CloneableEditorSupport.open(CloneableEditorSupport.java:436)
	at org.openide.awt.ActionDefaultPerfomer.actionPerformed(ActionDefaultPerfomer.java:70)
	at org.openide.awt.ContextAction$Performer.actionPerformed(ContextAction.java:226)
	at org.openide.awt.ContextManager.actionPerformed(ContextManager.java:260)
	at org.openide.awt.ContextAction.actionPerformed(ContextAction.java:109)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:93)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
	at org.openide.awt.GeneralAction$BaseDelAction.actionPerformed(GeneralAction.java:234)
	at org.openide.explorer.view.TreeView$PopupSupport.mouseClicked(TreeView.java:1609)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Operating System: Linux
Engine Version as used by the SDK: 3.2-stable

Graphics Capabilities
---------------------
FrameBuffer
FrameBufferMRT
FrameBufferMultisample
OpenGL20
OpenGL21
GLSL100
GLSL110
GLSL120
FloatTexture
NonPowerOfTwoTextures
VertexBufferArray
Multisample
FrameBufferBlit
TextureCompressionS3TC
TextureFilterAnisotropic
DepthTexture
IntegerIndexBuffer

**Comment by grizeldi** [comment] 2019-07-31 08:39
Is this a fresh install of the sdk and a freshly made tests project? When you create a tests project, the sdk copies the current engine version's test package. If that package changes in an engine update, problems like this can arise.

@MeFisto94 any chance we're using an outdated version of jme3-tests?

**Comment by zethan191** [comment] 2019-07-31 16:56
> Is this a fresh install of the sdk and a freshly made tests project? When you create a tests project, the sdk copies the current engine version's test package. If that package changes in an engine update, problems like this can arise.
> 
> @MeFisto94 any chance we're using an outdated version of jme3-tests?

Yes, it is the fresh installation of JMonkey v3.2.4-Stable-SDK1.
Here is the steps.

1. File -> New Project -> JME3 -> JME3 Tests
2. Navigate to "jme3test.texture" and try opening "tex3DThumb.j3md".

Thank you.

**Comment by MeFisto94** [comment] 2019-08-01 12:05
This seems like an issue on our side, because what fails is opening the j3md. Why? Because we try to use an absolute path instead of something based on the asset root. It could well be that tests don't follow the pattern to have an `assets/` folder and then something gets confused.

Usually we maintain our assets folder because that's also where the textures as shaders will be pulled in. 

Or does this only happen for this specific material definitions?

**Comment by zethan191** [comment] 2019-08-02 14:19
I notice it only happen to ".j3md" and ".texture" file extensions. I will let you know if I find more.

Thank you.

**Comment by MeFisto94** [comment] 2019-08-06 12:08
Sorry for replying so late, I replied by email but it didn't seem to work properly.
Can you copy the j3md and relevant files (if possible just the whole package) into a regular jme project under the asset directory? it should work there

@grizeldi The Problem is this: We load the j3md using an AssetManager, but I suspect the Tests Project does not contain an assets/ folder. Instead we have regular Java Packages and Resources.
We cannot easily fix this problem (as j3md will try to locate .frag and .vert using the AssetManager), so for now you have to copy the files back and forth.

**Comment by grizeldi** [comment] 2019-08-06 13:06
How do these tests work when using a gradle only setup then (no sdk)? You also need a root assets directory there.

**Comment by MeFisto94** [comment] 2019-08-06 13:08
I didn't look into it but I guess they have it in the resources folder and use the FileLocator/Resources Locator?

**Comment by sethanath** [comment] 2019-08-06 15:23
@ MeFisto94 commented 3 hours ago
"Sorry for replying so late, I replied by email but it didn't seem to work properly.
Can you copy the j3md and relevant files (if possible just the whole package) into a regular jme project under the asset directory? it should work there".

![Selection_001](https://user-images.githubusercontent.com/32467160/62552936-4dca9900-b823-11e9-92cd-4f803d290ac3.png)

The problem is gone now. I can open all the files with no problem.

Thank you so much.

**Comment by MeFisto94** [comment] 2020-02-16 20:43
so I am closing this issue for now, it looks like the files have been opened from inside a jar, which we just don't support currently.
In order to edit assets, they need to be in the assets/ folder.

**Closed by MeFisto94** 2020-02-16 20:43 UTC
