### ISSUE TITLE
Unable to run installer on macOS

### ISSUE THREAD

**Issue by swiftech** [jMonkeyEngine/sdk#229] opened 2020-01-31 04:22 UTC
Run the installer for macOS  and nothing appears. check the system log, it says:  
```
com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000001d.executable[6165]): Service exited with abnormal code: 4
```

jmonkeyplatform: 3.2.4-stable-sdk1
macOS Catalina: 10.15.2
jvm: 13.0.2

**Comment by MeFisto94** [comment] 2020-02-05 15:54
Sorry for the late reply, we are currently really busy because of the preparations for Google Summer of Code.
Could you try to open it from the terminal and see if you get the same results as https://github.com/jMonkeyEngine/sdk/issues/213 ?

**Comment by swiftech** [comment] 2020-02-09 06:09
yes, exactly the same error message, please merge this issue to that one.

**Comment by MeFisto94** [comment] 2020-02-10 22:00
Closing as duplicate of #213

**Closed by MeFisto94** 2020-02-10 22:00 UTC
