### ISSUE TITLE
The messy code in simplified Chinese

### ISSUE THREAD

**Issue by youmingfl** [jMonkeyEngine/sdk#123] opened 2017-04-14 00:14 UTC
I use Windows10_Pro_x64_15063.138 with simplified Chinese. I installed JME SDK for Windows_x64, but there was something wrong with character. There were many messy code in GUI. You can see it in screen shot.[http://bbs.jmecn.net/uploads/default/original/1X/4f3aee6755ce5350eb8e62e157e9c3fb4447e273.png](url)

**Comment by MeFisto94** [comment] 2017-04-15 12:13
Duplicate of #73
Suggestions of fonts are welcome. Maybe we can also find a font which is available on all platforms and monospaced?

@Relic724 maybe you remember where you found the fonts and/or have an idea on that.

**Closed by MeFisto94** 2017-04-15 12:13 UTC
Labels: Contribution welcome, DarkMonkey, duplicate

**Comment by wupei93** [comment] 2019-04-30 08:41
You can change appearance to windows mode.BTW, the version of my JME SDK is v3.2.2
![20190430162740](https://user-images.githubusercontent.com/41177812/56949922-c7892180-6b66-11e9-905c-7e2f44f3c728.jpg)
